---
- hosts: _control_plane
  become: yes
  tasks:
    - name: Inicializando Cluster
      shell: kubeadm init --pod-network-cidr=10.244.0.0/16 >> cluster_initialized.txt
      args:
        chdir: $HOME
        creates: cluster_initialized.txt

    - name: Criando diretorio .kube 
      become: yes
      become_user: ubuntu
      file:
        path: $HOME/.kube
        state: directory
        mode: 0755

    - name: Copiando admin.conf para kube config do usuario
      copy:
        src: /etc/kubernetes/admin.conf
        dest: /home/ubuntu/.kube/config
        remote_src: yes
        owner: ubuntu

    - name: Instalando Pod network
      become: yes
      become_user: ubuntu
      shell: kubectl apply -f ""https://github.com/weaveworks/weave/releases/download/v2.8.1/weave-daemonset-k8s.yaml" >> pod_network_setup.txt
      args:
        chdir: $HOME
        creates: pod_network_setup.txt

    - name: Repositorio do helm
      block:
       
        - name: Adicionando Chave publica para  Repo Helm
          shell:
            cmd: curl https://baltocdn.com/helm/signing.asc | gpg --dearmor | sudo tee /usr/share/keyrings/helm.gpg > /dev/nul

        
        
        - name: Adicionando Repo Helm
          ansible.builtin.apt_repository:
            repo: "deb [arch=amd64 signed-by=/usr/share/keyrings/helm.gpg] https://baltocdn.com/helm/stable/debian/ all main"
            state: present

    - name: Instlando Helm
      ansible.builtin.apt: 
        name:
        - helm
        update_cache: yes    
     
